services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: h-frontend
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: h-api
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/hotelki?schema=public
    volumes:
      - .:/app/api
      - /app//api/node_modules
    depends_on:
      # db:
      #   condition: service_healthy
      - db
    command: sh -c "sleep 10 && npx prisma migrate dev --name init && npm run start:prod"

  db:
    image: postgres:16
    container_name: pc-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hotelki
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U nest -d nest"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

volumes:
  postgres_data:
